import sqlite3
import os

base_dir = os.path.dirname(os.path.abspath(__file__))
db_path = os.path.join(base_dir, "../bd/data_base.db")
conn = sqlite3.connect(db_path)

cursor = conn.cursor()

cursor.execute(
    """
    CREATE TABLE IF NOT EXISTS photos (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        url TEXT NOT NULL,
        rocket_lunch bool NOT NULL
    )
    """
)

photos = [
    ( "https://i.imgur.com/bYnah57.jpeg", False),
    ( "https://i.imgur.com/1KefaOf.jpeg", False),
    ( "https://i.imgur.com/almtifg.jpeg", False),
    ( "https://i.imgur.com/UAzhFgQ.jpeg", False),
    ( "https://i.imgur.com/dv0Al6R.jpeg", False),
    ( "https://i.imgur.com/3KDCM5U.jpeg", False),
    ( "https://i.imgur.com/pr5MsGP.jpeg", False),
    ( "https://i.imgur.com/7w7ozmF.jpeg", False),
    ( "https://i.imgur.com/7w7ozmF.jpeg", False),
    ( "https://i.imgur.com/K8HS8NI.jpeg", False),
    ( "https://i.imgur.com/v0cdY6Q.jpeg", False),
    ( "https://i.imgur.com/aVXXZrA.jpeg", False),
    ( "https://i.imgur.com/P8PbWn5.jpeg", False),
    ( "https://i.imgur.com/gQoGPac.jpeg", False),
    ( "https://i.imgur.com/lncnDGE.jpeg", False),
    ( "https://i.imgur.com/UwPwyGW.jpeg", False),
    ( "https://i.imgur.com/3sdI0kG.jpeg", False),
    ( "https://i.imgur.com/3yqFr6S.jpeg", False),
    ( "https://i.imgur.com/Xn23Um9.jpeg", False),
    ( "https://i.imgur.com/xt9oZFH.jpeg", False),
    ( "https://i.imgur.com/MrcggEL.jpeg", False),
    ( "https://i.imgur.com/s9aoWTh.jpeg", False),
    ( "https://i.imgur.com/dxhlEpj.jpeg", False),
    ( "https://i.imgur.com/aSIF5I7.jpeg", False),
    ( "https://i.imgur.com/htJOaGo.jpeg", False),
    ( "https://i.imgur.com/TnahSbm.jpeg", False),
    ( "https://i.imgur.com/7MyAMNg.jpeg", False),
    ( "https://i.imgur.com/uv9tcOW.jpeg", False),
    ( "https://i.imgur.com/uv9tcOW.jpeg", False),
    ( "https://i.imgur.com/DN9U7oa.jpeg", False),
    ( "https://i.imgur.com/HwTQpd7.jpeg", False),
    ( "https://i.imgur.com/lPBXylv.jpeg", False),
    ( "https://i.imgur.com/cQxhfcy.jpeg", False),
    ( "https://i.imgur.com/OaVMSH4.jpeg", False),
    ( "https://i.imgur.com/SrobRBq.jpeg", False),
    ( "https://i.imgur.com/3X4OAmx.jpeg", False),
    ( "https://i.imgur.com/RNHKzKZ.jpeg", False),
    ( "https://i.imgur.com/UmpIs3a.jpeg", False),
    ( "https://i.imgur.com/OXhOBLR.jpeg", False),
    ( "https://i.imgur.com/nw8lcUY.jpeg", False),
    ( "https://i.imgur.com/wttPGzz.jpeg", False),
    ( "https://i.imgur.com/ki8chEk.jpeg", False),
    ( "https://i.imgur.com/v5gCgPb.jpeg", False),
    ( "https://i.imgur.com/J0hFX88.jpeg", False),
    ( "https://i.imgur.com/N9XxMjH.jpeg", False),
    ( "https://i.imgur.com/gCUGDK1.jpeg", False),
    ( "https://i.imgur.com/AeYdrwZ.jpeg", False),
    ( "https://i.imgur.com/wPuZ76d.jpeg", False),
    ( "https://i.imgur.com/oFd4VrN.jpeg", False),
    ( "https://i.imgur.com/pMFvUXg.jpeg", False),
    ( "https://i.imgur.com/qwxyegc.jpeg", False),
    ( "https://i.imgur.com/Tzwrq1R.jpeg", False),
    ( "https://i.imgur.com/1BziH5O.jpeg", False),
    ( "https://i.imgur.com/wEo3FqL.jpeg", False),
    ( "https://i.imgur.com/aot6jGK.jpeg", False),
    ( "https://i.imgur.com/WUs1rUA.jpeg", False),
    ( "https://i.imgur.com/i09xK87.jpeg", False),
    ( "https://i.imgur.com/2V8mqjf.jpeg", False),
    ( "https://i.imgur.com/7qUaDtl.jpeg", False),
    ( "https://i.imgur.com/dQccPQX.jpeg", False),
    ( "https://i.imgur.com/zKIzS3U.jpeg", False),
    ( "https://i.imgur.com/qiUTxgO.jpeg", False),
    ( "https://i.imgur.com/Yh2XAlS.jpeg", False),
    ( "https://i.imgur.com/2RhYf90.jpeg", False),
    ( "https://i.imgur.com/Zk9ZOIQ.jpeg", False),
    ( "https://i.imgur.com/Ez73ydX.jpeg", False),
    ( "https://i.imgur.com/NwDkZFa.jpeg", False),
    ( "https://i.imgur.com/Xd1p104.jpeg", False),
    ( "https://i.imgur.com/hgkNmy2.jpeg", False),
    ( "https://i.imgur.com/57nm4mX.jpeg", False),
    ( "https://i.imgur.com/57nm4mX.jpeg", False),
    ( "https://i.imgur.com/esOH32U.jpeg", False),
    ( "https://i.imgur.com/EmLuulI.jpeg", False),
    ( "https://i.imgur.com/Tfdep6b.jpeg", False),
    ( "https://i.imgur.com/xoHMa4b.jpeg", False),
    ( "https://i.imgur.com/mGRkWpw.jpeg", False),
    ( "https://i.imgur.com/R79FHj7.jpeg", False),
    ( "https://i.imgur.com/lB4HaPd.jpeg", False),
    ( "https://i.imgur.com/rldBhLm.jpeg", False),
    ( "https://i.imgur.com/rldBhLm.jpeg", False),
    ( "https://i.imgur.com/Pagyepj.jpeg", False),
    ( "https://i.imgur.com/Pagyepj.jpeg", True),
    ( "https://i.imgur.com/kDG2v4d.jpeg", True),
    ( "https://i.imgur.com/Q3tAFJy.jpeg", True),
    ( "https://i.imgur.com/ByviAcn.jpeg", True),
    ( "https://i.imgur.com/lqUFbDe.jpeg", True),
    ( "https://i.imgur.com/jpQ2XuE.jpeg", True),
    ( "https://i.imgur.com/0MCBXXA.jpeg", True),
    ( "https://i.imgur.com/R82Wasu.jpeg", True),
    ( "https://i.imgur.com/wga0D79.jpeg", True),
    ( "https://i.imgur.com/nKfk9aH.jpeg", True),
    ( "https://i.imgur.com/kAOHJQE.jpeg", True),
    ( "https://i.imgur.com/EgFNcSb.jpeg", True),
    ( "https://i.imgur.com/EEaYcDp.jpeg", True),
    ( "https://i.imgur.com/g9ueaog.jpeg", False),
    ( "https://i.imgur.com/KFZJoVa.jpeg", False),
    ( "https://i.imgur.com/cZAzmn5.jpeg", False),
    ( "https://i.imgur.com/jX9e36I.jpeg", False),
    ( "https://i.imgur.com/Jj9K3Em.jpeg", False),
    ( "https://i.imgur.com/RahCBDE.jpeg", False),
    ( "https://i.imgur.com/I4AeZNU.jpeg", False),
    ( "https://i.imgur.com/F5E7qj1.jpeg", False),
    ( "https://i.imgur.com/iLDuZbI.jpeg", False),
    ( "https://i.imgur.com/zwUjfbE.jpeg", False),
    ( "https://i.imgur.com/Cg8lLv9.jpeg", False),
    ( "https://i.imgur.com/P7KMovl.jpeg", False),
    ( "https://i.imgur.com/fVEAKN1.jpeg", False),
    ( "https://i.imgur.com/ww4fP3t.jpeg", False),
    ( "https://i.imgur.com/JYQkxsX.jpeg", False),
    ( "https://i.imgur.com/g6W1Clk.jpeg", False),
    ( "https://i.imgur.com/zXSQsml.jpeg", False),
    ( "https://i.imgur.com/nVB74oX.jpeg", False),
    ( "https://i.imgur.com/TzmPAgX.jpeg", False),
    ( "https://i.imgur.com/TzmPAgX.jpeg", False),
    ( "https://i.imgur.com/u49E1X1.jpeg", False),
    ( "https://i.imgur.com/91Lmd6Q.jpeg", False),
    ( "https://i.imgur.com/91Lmd6Q.jpeg", False),
    ( "https://i.imgur.com/4SuYwsi.jpeg", False),
    ( "https://i.imgur.com/6iIlB7M.jpeg", False),
    ( "https://i.imgur.com/XAkyXrq.jpeg", False),
    ( "https://i.imgur.com/HsNnaMZ.jpeg", False),
    ( "https://i.imgur.com/HsNnaMZ.jpeg", False),
    ( "https://i.imgur.com/HsNnaMZ.jpeg", False),
]
cursor.executemany('''
    INSERT INTO photos (url, rocket_lunch)
    VALUES ( ?, ?)
''', photos)

conn.commit()

conn.close()
